#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Everything captured here is a prod/CI credential — keep it OUT of .env.local
# (a CONVEX_DEPLOY_KEY there would point every local `convex` command at prod).
# .env.deploy.local is gitignored (.env.*.local) and read by nothing but this
# wizard, which uses it to remember values across re-runs.
ENV_FILE=".env.deploy.local"

# ── stage-local helpers ────────────────────────────────────────────────────
# env_local KEY — read a dev value from .env.local (to reuse for the dev env).
env_local() {
  [[ -f .env.local ]] || return 1
  local line; line=$(grep -E "^${1}=" .env.local | tail -n1) || return 1
  printf '%s' "${line#*=}"
}
# mask VALUE — enough of a key to recognise it, no more.
mask() {
  local v="$1"
  if (( ${#v} > 12 )); then printf '%s…%s' "${v:0:8}" "${v: -4}"; else printf '%s' "$v"; fi
}
# expect_prefix VALUE PREFIX "what" — warn (don't stop) on a suspicious paste.
expect_prefix() {
  [[ "$1" == "$2"* ]] || warn "$3 normally starts with '$2' — double-check you copied the right thing."
}
# ask_secret_prefixed KEY "Prompt" PREFIX "what" — like ask_secret, but keeps
# asking until the value has the expected prefix: a wrong paste here (e.g. a
# Cloudflare Account ID where a Convex key belongs) only surfaces as a failed
# CI run, so it's worth blocking on.
ask_secret_prefixed() {
  local key="$1" prompt="$2" prefix="$3" what="$4"
  while :; do
    ask_secret "$key" "$prompt"
    [[ "${!key}" == "$prefix"* ]] && return 0
    warn "$what starts with '$prefix' — that paste didn't. Copy the key itself (not an ID or token from another tab) and try again."
    # A wrong value already saved from an earlier run must not keep coming back as the default.
    [[ -f "$ENV_FILE" ]] && sed -i.bak -E "/^${key}=/d" "$ENV_FILE" && rm -f "$ENV_FILE.bak"
  done
}
# cf_wrangler ARGS… — wrangler authed with the captured token, pinned to the
# root config (explicit -c skips the build-output redirect, so the target
# Worker never depends on whichever env was built last).
cf_wrangler() {
  CLOUDFLARE_API_TOKEN="$CLOUDFLARE_API_TOKEN" CLOUDFLARE_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID" \
    bunx wrangler -c wrangler.jsonc "$@"
}
# worker_secret VALUE [--env dev] — store CLERK_SECRET_KEY on a Worker. Before
# the first deploy wrangler creates a draft Worker of that name — that's fine.
worker_secret() {
  local value="$1"; shift
  local target="jrny-spark"; [[ "$*" == *"--env dev"* ]] && target="jrny-spark-dev"
  if printf '%s' "$value" | cf_wrangler secret put CLERK_SECRET_KEY "$@" >/dev/null 2>&1; then
    printf '  %s✓ set%s Worker secret CLERK_SECRET_KEY on %s\n' "$GREEN" "$RESET" "$target"
  else
    SKIPPED+=("Worker secret on $target: printf '%s' '<value>' | bunx wrangler -c wrangler.jsonc secret put CLERK_SECRET_KEY $*")
    warn "wrangler secret put failed for $target — set it by hand later (see summary)."
  fi
}
# convex_env_set KEY NAME VALUE — set an env var on the deployment a deploy key
# points at, then read it back as proof it landed.
convex_env_set() {
  local key="$1" name="$2" value="$3"
  if CONVEX_DEPLOY_KEY="$key" bunx convex env set "$name" "$value" >/dev/null 2>&1 \
     && [[ "$(CONVEX_DEPLOY_KEY="$key" bunx convex env get "$name" 2>/dev/null)" == *"$value"* ]]; then
    printf '  %s✓ set%s Convex env %s = %s\n' "$GREEN" "$RESET" "$name" "$value"
  else
    SKIPPED+=("Convex env $name=$value — dashboard → deployment → Settings → Environment Variables")
    warn "couldn't set $name via the CLI — do it in the dashboard (see summary)."
  fi
}

banner "Spark — Cloudflare + Convex + Clerk deploy setup"

# ── 1 ──────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools this wizard drives (gh, bun, git, wrangler, convex)…"
missing=0
for tool in gh bun git; do
  command -v "$tool" >/dev/null 2>&1 || { warn "$tool not found on PATH"; missing=1; }
done
if command -v gh >/dev/null 2>&1 && ! gh auth status >/dev/null 2>&1; then
  warn "gh is not logged in — run 'gh auth login' first (GitHub secrets/vars are written with gh)."
  missing=1
fi
if (( missing )); then warn "Fix the above and re-run. Nothing has been changed."; exit 1; fi
if [[ ! -x node_modules/.bin/wrangler || ! -x node_modules/.bin/convex ]]; then
  say "Installing dependencies (bun install)…"; bun install
fi
repo=$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo "?")
say "GitHub repo: ${BOLD}${repo}${RESET} — secrets/vars land there."
DEV_DEPLOYMENT=$(env_local CONVEX_DEPLOYMENT || true); DEV_DEPLOYMENT="${DEV_DEPLOYMENT#dev:}"
if [[ -n "$DEV_DEPLOYMENT" ]]; then
  say "Convex dev deployment (from .env.local): ${BOLD}${DEV_DEPLOYMENT}${RESET}"
else
  note "No CONVEX_DEPLOYMENT in .env.local — run 'bun run dev:convex' once first if you want the dev environment."
fi
note "Captured values are saved to $ENV_FILE (gitignored) so a re-run can keep them."
pause

# ── 2 ──────────────────────────────────────────────────────────────────────
stage "Cloudflare — API token"
say "CI (and this wizard) deploy Workers with this token."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → find 'Edit Cloudflare Workers' → Use template."
step "Account Resources: Include → your account. Zone Resources: leave as All zones (spark.jrny.app later)."
step "Continue to summary → Create Token → copy it (shown only once)."
while :; do
  ask_secret CLOUDFLARE_API_TOKEN "Paste the API token:"
  say "Verifying the token with Cloudflare…"
  WHOAMI=$(CLOUDFLARE_API_TOKEN="$CLOUDFLARE_API_TOKEN" bunx wrangler whoami 2>&1 || true)
  if grep -q "Account ID" <<<"$WHOAMI"; then
    say "${GREEN}✓${RESET} token accepted"
    break
  fi
  warn "Cloudflare rejected that token (a real one is 40 characters of letters, digits, - and _). Copy the token value itself — not the token name, ID, or the Account ID — and try again."
  [[ -f "$ENV_FILE" ]] && sed -i.bak -E "/^CLOUDFLARE_API_TOKEN=/d" "$ENV_FILE" && rm -f "$ENV_FILE.bak"
done
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
set_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"

# ── 3 ──────────────────────────────────────────────────────────────────────
stage "Cloudflare — Account ID + workers.dev subdomain"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Right sidebar → Account details → copy the Account ID (32 hex chars)."
step "Same sidebar: if it offers to set up a workers.dev subdomain, do it — the first deploy needs one."
# The verified token's account list (from stage 2) is the source of truth —
# the ID must be one of those accounts, or every deploy fails later.
while :; do
  ask CLOUDFLARE_ACCOUNT_ID "Paste the Account ID:"
  if grep -qi "$CLOUDFLARE_ACCOUNT_ID" <<<"$WHOAMI"; then
    say "${GREEN}✓${RESET} that account is one the token can access"
    break
  fi
  warn "That ID isn't among the accounts this token can see. Accounts the token reaches:"
  grep -E "│" <<<"$WHOAMI" | sed 's/^/    /' || true
  [[ -f "$ENV_FILE" ]] && sed -i.bak -E "/^CLOUDFLARE_ACCOUNT_ID=/d" "$ENV_FILE" && rm -f "$ENV_FILE.bak"
done
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
set_secret CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"

# ── 4 ──────────────────────────────────────────────────────────────────────
stage "Convex — production deploy key"
say "CI pushes functions to the PROD deployment with this key; the wizard also uses it to set an env var there."
open_url "https://dashboard.convex.dev/deployment/settings"
step "Deployment switcher (top-left) → Production, in the jrny-spark project."
step "Settings → Deploy keys → Generate a deploy key."
step "Choose full CLI access, not the deploy-only scope — CI also runs 'convex run seed:seedDecks' and this wizard sets env vars."
step "Copy the key (starts with prod:)."
ask_secret_prefixed CONVEX_DEPLOY_KEY "Paste the production deploy key:" "prod:" "A production deploy key"
write_env CONVEX_DEPLOY_KEY "$CONVEX_DEPLOY_KEY"
set_secret CONVEX_DEPLOY_KEY "$CONVEX_DEPLOY_KEY"

# ── 5 ──────────────────────────────────────────────────────────────────────
stage "Convex — dev deploy key"
say "The dev Worker uses your existing dev deployment${DEV_DEPLOYMENT:+ ($DEV_DEPLOYMENT)} — the same one 'bun run dev:convex' uses."
open_url "https://dashboard.convex.dev/deployment/settings"
step "Deployment switcher → your dev deployment${DEV_DEPLOYMENT:+ ($DEV_DEPLOYMENT)}."
step "Settings → Deploy keys → Generate (full CLI access again) → copy (starts with dev:)."
ask_secret_prefixed CONVEX_DEPLOY_KEY_DEV "Paste the dev deploy key:" "dev:" "A dev deploy key"
write_env CONVEX_DEPLOY_KEY_DEV "$CONVEX_DEPLOY_KEY_DEV"
set_secret CONVEX_DEPLOY_KEY_DEV "$CONVEX_DEPLOY_KEY_DEV"

# ── 6 ──────────────────────────────────────────────────────────────────────
stage "Clerk — production instance keys"
say "Prod sign-in uses a Clerk PRODUCTION instance on jrny.app — Google + Apple OAuth only, no passwords (PRD §6.1)."
open_url "https://dashboard.clerk.com/last-active?path=api-keys"
step "Instance switcher (top bar) → Production. None yet? Create it for the domain jrny.app; in Configure → SSO connections enable Google + Apple and nothing else."
note "A production instance needs DNS records on jrny.app (Configure → Domains) before sign-in works; the keys exist right away."
step "API keys → copy the Publishable key (pk_live_…)."
ask VITE_CLERK_PUBLISHABLE_KEY "Paste the production publishable key:"
expect_prefix "$VITE_CLERK_PUBLISHABLE_KEY" "pk_live_" "A production publishable key"
write_env VITE_CLERK_PUBLISHABLE_KEY "$VITE_CLERK_PUBLISHABLE_KEY"
set_var VITE_CLERK_PUBLISHABLE_KEY "$VITE_CLERK_PUBLISHABLE_KEY"
step "Reveal + copy the Secret key (sk_live_…) — it goes onto the prod Worker, never into GitHub."
ask_secret CLERK_SECRET_KEY_PROD "Paste the production secret key:"
expect_prefix "$CLERK_SECRET_KEY_PROD" "sk_live_" "A production secret key"
write_env CLERK_SECRET_KEY_PROD "$CLERK_SECRET_KEY_PROD"
say "Storing it as a runtime secret on the prod Worker (jrny-spark)…"
worker_secret "$CLERK_SECRET_KEY_PROD"

# ── 7 ──────────────────────────────────────────────────────────────────────
stage "Clerk ↔ Convex — production JWT template + issuer domain"
say "Convex verifies Clerk sessions via a JWT template named 'convex' and the instance's Frontend API URL."
open_url "https://dashboard.clerk.com/apps/setup/convex"
step "With the Production instance selected, turn the Convex integration on — Clerk creates the 'convex' JWT template and shows the Frontend API URL (https://clerk.jrny.app)."
note "Manual route if that page looks different: Configure → JWT templates → New template → Convex (keep the name 'convex'); the Frontend API URL is on the API keys page."
ask CLERK_JWT_ISSUER_DOMAIN_PROD "Paste the production Frontend API URL (https://…):"
expect_prefix "$CLERK_JWT_ISSUER_DOMAIN_PROD" "https://" "A Frontend API URL"
write_env CLERK_JWT_ISSUER_DOMAIN_PROD "$CLERK_JWT_ISSUER_DOMAIN_PROD"
say "Setting CLERK_JWT_ISSUER_DOMAIN on the PROD Convex deployment (convex/auth.config.ts reads it)…"
convex_env_set "$CONVEX_DEPLOY_KEY" CLERK_JWT_ISSUER_DOMAIN "$CLERK_JWT_ISSUER_DOMAIN_PROD"

# ── 8 ──────────────────────────────────────────────────────────────────────
stage "Clerk — dev instance (reuses your local keys)"
say "The dev Worker uses the Clerk DEVELOPMENT instance — the pk_test/sk_test pair already in .env.local."
pk_dev=$(env_local VITE_CLERK_PUBLISHABLE_KEY || true)
sk_dev=$(env_local CLERK_SECRET_KEY || true)
iss_dev=$(env_local CLERK_JWT_ISSUER_DOMAIN || true)
if [[ -n "$pk_dev" && -n "$sk_dev" ]]; then
  say "Found in .env.local: publishable $(mask "$pk_dev"), secret $(mask "$sk_dev")${iss_dev:+, issuer $iss_dev}."
  if ! confirm "Use these for the dev environment?"; then pk_dev=""; sk_dev=""; iss_dev=""; fi
fi
if [[ -z "$pk_dev" || -z "$sk_dev" ]]; then
  open_url "https://dashboard.clerk.com/last-active?path=api-keys"
  step "Instance switcher → Development → copy the Publishable key (pk_test_…) and the Secret key (sk_test_…)."
  ask pk_dev "Paste the dev publishable key:"
  ask_secret sk_dev "Paste the dev secret key:"
fi
if [[ -z "$iss_dev" ]]; then
  step "Frontend API URL of the Development instance (https://<slug>.clerk.accounts.dev — API keys page)."
  ask iss_dev "Paste the dev Frontend API URL:"
fi
expect_prefix "$pk_dev" "pk_test_" "A dev publishable key"
expect_prefix "$sk_dev" "sk_test_" "A dev secret key"
write_env VITE_CLERK_PUBLISHABLE_KEY_DEV "$pk_dev"
set_var VITE_CLERK_PUBLISHABLE_KEY_DEV "$pk_dev"
say "Storing the dev secret on the dev Worker (jrny-spark-dev)…"
worker_secret "$sk_dev" --env dev
say "Making sure the DEV Convex deployment has the dev issuer domain (idempotent)…"
convex_env_set "$CONVEX_DEPLOY_KEY_DEV" CLERK_JWT_ISSUER_DOMAIN "$iss_dev"
note "Dev instances aren't domain-restricted, so jrny-spark-dev.*.workers.dev works without extra Clerk config."

# ── 9 ──────────────────────────────────────────────────────────────────────
stage "First deploy — push main (prod), optionally create dev"
say "Everything CI needs is in place. Pushing to main runs .github/workflows/deploy.yml → prod."
say "Working tree right now:"
git status --short | sed 's/^/    /'
note "Only the deploy-related files get staged — anything else stays untracked."
if confirm "Commit the deploy setup and push to main now?"; then
  git add .github wrangler.jsonc vite.config.ts package.json bun.lock scripts/build-pwa.ts \
          scripts/setup-deploy.sh src/components/RegisterSW.tsx README.md .gitignore
  git commit -m "Wire Cloudflare Workers deploy (prod + dev envs), CI, and PWA update prompt" \
    || note "nothing new to commit"
  git push origin main
  say "Watching the deploy run (Ctrl-C stops watching; the run keeps going)…"
  sleep 6
  run_id=$(gh run list --workflow=deploy.yml --branch=main -L1 --json databaseId -q '.[0].databaseId' 2>/dev/null || true)
  if [[ -n "$run_id" ]]; then
    gh run watch "$run_id" --exit-status || warn "the run failed — inspect it: gh run view $run_id --log-failed"
  else
    warn "couldn't find the run yet — check: gh run list --workflow=deploy.yml"
  fi
else
  SKIPPED+=("commit + push to main to trigger the first prod deploy")
fi
if confirm "Also create a 'dev' branch from main and push it (triggers the first dev deploy)?"; then
  git branch dev 2>/dev/null || true
  git push -u origin dev
else
  note "Any branch can still be deployed to the dev Worker: gh workflow run deploy.yml --ref <branch>"
fi
note "Later, once jrny.app is on Cloudflare: uncomment 'routes' in wrangler.jsonc → spark.jrny.app."
pause

finish
