/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesNewRouteImport } from './routes/games/new'
import { Route as PlayIndexRouteImport } from './routes/play/index'
import { Route as PlayRecapRouteImport } from './routes/play/recap'
import { Route as PlaySetupRouteImport } from './routes/play/setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNewRoute = GamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRecapRoute = PlayRecapRouteImport.update({
  id: '/play/recap',
  path: '/play/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySetupRoute = PlaySetupRouteImport.update({
  id: '/play/setup',
  path: '/play/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/games/new': typeof GamesNewRoute
  '/play/recap': typeof PlayRecapRoute
  '/play/setup': typeof PlaySetupRoute
  '/games/': typeof GamesIndexRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/games/new': typeof GamesNewRoute
  '/play/recap': typeof PlayRecapRoute
  '/play/setup': typeof PlaySetupRoute
  '/games': typeof GamesIndexRoute
  '/play': typeof PlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/games/new': typeof GamesNewRoute
  '/play/recap': typeof PlayRecapRoute
  '/play/setup': typeof PlaySetupRoute
  '/games/': typeof GamesIndexRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/settings'
    | '/sign-in'
    | '/games/new'
    | '/play/recap'
    | '/play/setup'
    | '/games/'
    | '/play/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/settings'
    | '/sign-in'
    | '/games/new'
    | '/play/recap'
    | '/play/setup'
    | '/games'
    | '/play'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/settings'
    | '/sign-in'
    | '/games/new'
    | '/play/recap'
    | '/play/setup'
    | '/games/'
    | '/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  GamesNewRoute: typeof GamesNewRoute
  PlayRecapRoute: typeof PlayRecapRoute
  PlaySetupRoute: typeof PlaySetupRoute
  GamesIndexRoute: typeof GamesIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/new': {
      id: '/games/new'
      path: '/games/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof GamesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/recap': {
      id: '/play/recap'
      path: '/play/recap'
      fullPath: '/play/recap'
      preLoaderRoute: typeof PlayRecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/setup': {
      id: '/play/setup'
      path: '/play/setup'
      fullPath: '/play/setup'
      preLoaderRoute: typeof PlaySetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  GamesNewRoute: GamesNewRoute,
  PlayRecapRoute: PlayRecapRoute,
  PlaySetupRoute: PlaySetupRoute,
  GamesIndexRoute: GamesIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
